# Generated by Django 2.2.7 on 2019-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesmentAtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitehousesalaries',
            name='position_title',
            field=models.CharField(max_length=150),
        ),
    ]
